services:
  booker-db:
    restart: always
    container_name: booker-db
    image: postgres:16
    env_file: ./postgresql-db/.pg-env
    ports:
      - "5433:5432"
    volumes:
      - ./postgresql-db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  booker-api:
    restart: always
    container_name: booker-api
    build: ./src
    command: sh -c "python manage.py migrate && gunicorn api.wsgi:application -b 0.0.0.0:8000"
    working_dir: /src
    ports:
      - "8000:8000"
    depends_on:
      booker-db:
        condition: service_healthy